apiVersion: v1
kind: Service
metadata:
  labels:
    app: executor
    environment: Development
  name: executor
  namespace: sirius
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  - name: grpc
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: executor
  sessionAffinity: None
  type: ClusterIP
