apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: VaultAgent Worker
  labels:
    app: vault-agent-worker
    environment: Development
    tier: Service
  name: vault-agent-worker
  namespace: sirius
spec:
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: vault-agent-worker
  template:
    metadata:
      labels:
        app: vault-agent-worker
      name: vault-agent-worker
    spec:
      containers:
      - name: vault-agent-worker
        image: docker.io/swisschains/sirius-vault-agent-worker:1.1.7
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command:
             - /bin/sh
             - -c 
             - "/bin/echo 'options single-request-reopen' >> /etc/resolv.conf"
        ports:
        - containerPort: 5000
        - containerPort: 5001
        readinessProbe:
          httpGet:
            path: /api/isalive
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/isalive
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 20
        resources:
          requests:
            memory: 64Mi 
            cpu: 40m 
          limits:
            memory: 128Mi 
            cpu: 500m 
        env:
        - name: RemoteSettingsRequired
          value: "true"
        - name: RemoteSettingsUrls__0 
          value: "http://settings.sirius.svc.cluster.local/common"
        - name: RemoteSettingsUrls__1 
          value: "http://settings.sirius.svc.cluster.local/sirius/common"
        - name: RemoteSettingsUrls__2
          value: "http://settings.sirius.svc.cluster.local/sirius/vault-agent"
      tolerations:
       - effect: NoSchedule
         operator: Exists
      nodeSelector:
          agentpool: sirius