apiVersion: v1
kind: Service
metadata:
  labels:
    app: brokerage-worker
    environment: Development
  name: brokerage-worker
  namespace: sirius
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: brokerage-worker
  sessionAffinity: None
  type: ClusterIP
