apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc
    environment: dev
  name: grpc
  namespace: tools
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 6969
    name: http
  selector:
    app: grpc
  sessionAffinity: None
  type: ClusterIP
