apiVersion: v1
kind: Service
metadata:
  labels:
    app: tenants
    environment: Development
  name: tenants
  namespace: universe
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  - name: grpc
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: tenants
  sessionAffinity: None
  type: ClusterIP
