apiVersion: v1
kind: Service
metadata:
  labels:
    app: settings
    environment: Development
  name: settings
  namespace: sirius
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: settings
  sessionAffinity: None
  type: ClusterIP