apiVersion: v1
kind: Service
metadata:
  labels:
    app: key-keeper-api-worker
    environment: Development
  name: key-keeper-api-worker
  namespace: sirius
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: key-keeper-api-worker
  sessionAffinity: None
  type: ClusterIP
