apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
    environment: Development
  name: api
  namespace: universe
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: api
  sessionAffinity: None
  type: LoadBalancer
