apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbit
    environment: dev
  name: rabbit
  namespace: sirius
#  annotations:
#    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - name: "5672"
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: "15672"
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbit
  sessionAffinity: None
  type: ClusterIP
#  type: LoadBalancer
