apiVersion: v1
kind: Service
metadata:
  labels:
    app: key-keeper-api
    environment: Development
  name: key-keeper-api
  namespace: sirius
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  loadBalancerIP: 192.168.19.6
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 5000
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: 5001  
  selector:
    app: key-keeper-api
  sessionAffinity: None
  type: LoadBalancer
