apiVersion: v1
kind: Service
metadata:
  labels:
    app: indexer-worker-1
    environment: Development
  name: indexer-worker-1
  namespace: sirius-indexers
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: indexer-worker-1
  sessionAffinity: None
  type: ClusterIP
