apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Monitoring-Seq
  labels:
    app: seq-proxy
    environment: Production
    tier: nginx-proxy
  name: seq-proxy
  namespace: sirius-monitoring
spec:
  revisionHistoryLimit: 5
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: seq-proxy
  template:
    metadata:
      labels:
        app: seq-proxy
      name: seq-proxy
    spec:
      #tolerations:
      #- effect: NoSchedule
      #  operator: Exists
      tolerations:
       - effect: NoSchedule
         operator: Exists
      nodeSelector:
        agentpool: sirius
      containers:
      - name: seq-proxy
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /probe
            port: 81
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /probe
            port: 81
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "100Mi"
            cpu: 0.1
          limits:
            memory: "512Mi"
            cpu: 2
        env:
          - name: version
            value: "1.0.1"

        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: seq-proxy
          subPath: nginx.conf
        - mountPath: /etc/nginx/conf.d/default.conf
          name: seq-proxy
          subPath: default.conf
        - mountPath: /etc/nginx/conf.d/default.stream
          name: seq-proxy
          subPath: default.stream
      volumes:
      - configMap:
          defaultMode: 0550
          name: seq-proxy
        name: seq-proxy
