apiVersion: apps/v1
kind: Deployment
metadata:
  name: pritunl-vpn
  namespace: infrastructure
spec:
  revisionHistoryLimit: 5
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: pritunl-vpn
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pritunl-vpn
      name: pritunl-vpn
    spec:
      terminationGracePeriodSeconds: 60
      tolerations:
      - effect: NoSchedule
        operator: Exists
#      nodeSelector:
#         type: Monitoring-1
      containers:
        - image: scrooge/pritunl:v1.29.2276.91
          name: pritunl-vpn
          imagePullPolicy: Always
          env:
            - name: MONGODB_SERVER
              value: "pritunl-vpn-mongo.infrastructure"
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 1194
              protocol: TCP
          securityContext:
            privileged: true
