apiVersion: v1
kind: Service
metadata:
  name: pritunl-vpn
  namespace: infrastructure
spec:
  type: LoadBalancer
  ports:
    - port: 1194
      targetPort: 1194
      name: openvpn
    - port: 80
      protocol: "TCP"
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      protocol: "TCP"
      name: https
  selector:
    app: pritunl-vpn
