apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: indexer
  labels:
    app: indexer
    environment: Development
    tier: Service
  name: indexer
  namespace: sirius-indexers
spec:
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: indexer
  template:
    metadata:
      labels:
        app: indexer
      name: indexer
    spec:
      containers:
      - name: indexer
        image: docker.io/swisschains/sirius-indexer:0.1.14
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command:
             - /bin/sh
             - -c 
             - "/bin/echo 'options single-request-reopen' >> /etc/resolv.conf"
        ports:
        - containerPort: 5000
        - containerPort: 5001
        readinessProbe:
          httpGet:
            path: /api/isalive
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/isalive
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 20
        resources:
          requests:
            memory: 64Mi 
            cpu: 40m 
          limits:
            memory: 128Mi 
            cpu: 500m 
        env:
        - name: RemoteSettingsRequired
          value: "true"
        - name: RemoteSettingsUrls__0 
          value: "http://settings.sirius.svc.cluster.local/common"
        - name: RemoteSettingsUrls__1
          value: "http://settings.sirius.svc.cluster.local/sirius/common"
        - name: RemoteSettingsUrls__2
          value: "http://settings.sirius.svc.cluster.local/sirius-indexers/common"
        - name: RemoteSettingsUrls__3
          value: "http://settings.sirius.svc.cluster.local/sirius-indexers/indexer-1"
        - name: RemoteSettingsUrls__4
          value: "http://settings.sirius.svc.cluster.local/sirius-indexers/indexer-2"
        - name: RemoteSettingsUrls__5
          value: "http://settings.sirius.svc.cluster.local/sirius-indexers/indexer-3"
        - name: RemoteSettingsUrls__6
          value: "http://settings.sirius.svc.cluster.local/sirius-indexers/indexer-4"
        - name: RemoteSettingsUrls__7
          value: "http://settings.sirius.svc.cluster.local/sirius-indexers/indexer-5"          
      tolerations:
       - effect: NoSchedule
         operator: Exists
      nodeSelector:
        agentpool: sirindexers
