apiVersion: v1
kind: Service
metadata:
  labels:
    app: portal
    environment: Development
  name: portal
  namespace: universe
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: portal
  sessionAffinity: None
  type: ClusterIP
