apiVersion: v1
kind: Service
metadata:
  labels:
    app: portal
    environment: Development
  name: portal
  namespace: universe
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  loadBalancerIP: 192.168.19.5
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: portal
  sessionAffinity: None
  type: LoadBalancer
