apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Rabbit
  labels:
    app: rabbit-proxy
    environment: Production
    tier: nginx-proxy
  name: rabbit-proxy
  namespace: sirius
spec:
  revisionHistoryLimit: 5
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: rabbit-proxy
  template:
    metadata:
      labels:
        app: rabbit-proxy
      name: rabbit-proxy
    spec:
      #tolerations:
      #- effect: NoSchedule
      #  operator: Exists
      #nodeSelector:
      #  type: SERVICES
      containers:
      - name: rabbit-proxy
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
        - containerPort: 15672
        readinessProbe:
          httpGet:
            path: /probe
            port: 81
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /probe
            port: 81
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "100Mi"
            cpu: 0.1
          limits:
            memory: "512Mi"
            cpu: 2
        env:
          - name: version
            value: "1.0.1"

        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: rabbit-proxy
          subPath: nginx.conf
        - mountPath: /etc/nginx/conf.d/default.conf
          name: rabbit-proxy
          subPath: default.conf
        - mountPath: /etc/nginx/conf.d/default.stream
          name: rabbit-proxy
          subPath: default.stream
      volumes:
      - configMap:
          defaultMode: 0550
          name: rabbit-proxy
        name: rabbit-proxy
