apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbit-proxy
    environment: Production
  name: rabbit
  namespace: sirius
spec:
  ports:
  - name: tcp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: web
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: probe
    port: 81
    protocol: TCP
    targetPort: 81
  selector:
    app: rabbit-proxy
  sessionAffinity: None
  type: ClusterIP
