apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault-api
    environment: Development
  name: vault-api
  namespace: sirius
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 5000
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: 5001
  selector:
    app: vault-api
  sessionAffinity: None
  type: LoadBalancer
