apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Swisschain Mpngo VPN
  labels:
    app: pritunl-vpn-mongo
    environment: prod
  name: pritunl-vpn-mongo
  namespace: infrastructure
spec:
  revisionHistoryLimit: 5
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: pritunl-vpn-mongo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pritunl-vpn-mongo
      name: pritunl-vpn-mongo
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      nodeSelector:
        agentpool: databases
#      nodeSelector:
#        kubernetes.io/hostname: k8s-test-p-node-3
      containers:
      - name: mongo-vpn
        image: mongo:3.4.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
          periodSeconds: 20

        volumeMounts:
        - name: mongodb-vpn
          mountPath: /data/db

      volumes:
      - name: mongodb-vpn
        azureDisk:
          kind: Managed
          diskName: mongodb-vpn
          diskURI: ...

