apiVersion: v1
kind: Service
metadata:
  labels:
    app: pritunl-vpn-mongo
    environment: prod
  name: pritunl-vpn-mongo
  namespace: infrastructure
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: pritunl-vpn-mongo
  sessionAffinity: None
  type: ClusterIP
