apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: HSM Vault Shared
  labels:
    app: vault-hsm-shared
    environment: Development
    tier: Service
  name: vault-hsm-shared
  namespace: sirius
spec:
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: vault-hsm-shared
  template:
    metadata:
      labels:
        app: vault-hsm-shared
      name: vault-hsm-shared
    spec:
      containers:
      - name: vault-hsm-shared
        image: docker.io/swisschains/sirius-vault-hsm:1.0.1
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command:
             - /bin/sh
             - -c 
             - "/bin/echo 'options single-request-reopen' >> /etc/resolv.conf"
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /api/isalive
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /api/isalive
            port: 5000
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            memory: 128Mi
            cpu: 40m 
          limits:
            memory: 500Mi
            cpu: 500m 
        env:
        - name: VAULT_CONFIG
          value: "http://settings.sirius.svc.cluster.local/sirius/vault-hsm-shared"
        - name: JAVA_OPTS
          value: "-Xms64m -Xmx128m"
      tolerations:
       - effect: NoSchedule
         operator: Exists
      nodeSelector:
        agentpool: sirius
