apiVersion: v1
kind: Service
metadata:
  labels:
    app: pulsar-worker
    environment: Development
  name: pulsar-worker
  namespace: sirius
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: pulsar-worker
  sessionAffinity: None
  type: ClusterIP
