apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    environment: Production
    tier: jobs
  name: redis
  namespace: sirius
spec:
  ports:
  - name: tcp
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
