name: Deploy test

on:
  push:
    branches: [ test ]
    paths:
    - 'Namespaces/**'
    - 'Pods/**'    
    
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy
      uses: swisschain/kubeapplyall@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_TEST }}
