apiVersion: v1
kind: Service
metadata:
  labels:
    app: quasar
    environment: Development
  name: quasar
  namespace: quasar
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  - name: grpc
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: quasar
  sessionAffinity: None
  type: ClusterIP
